# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temperature.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(764, 423)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fahrenlabel = QtWidgets.QLabel(self.centralwidget)
        self.fahrenlabel.setGeometry(QtCore.QRect(20, 70, 241, 51))
        self.fahrenlabel.setObjectName("fahrenlabel")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(280, 81, 161, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 250, 241, 51))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 250, 161, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.Fahrenbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Fahrenbutton.setGeometry(QtCore.QRect(30, 160, 93, 28))
        self.Fahrenbutton.setObjectName("Fahrenbutton")
        self.result1 = QtWidgets.QLabel(self.centralwidget)
        self.result1.setGeometry(QtCore.QRect(290, 160, 231, 21))
        self.result1.setText("")
        self.result1.setObjectName("result1")
        self.Celcbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Celcbutton.setGeometry(QtCore.QRect(30, 330, 93, 28))
        self.Celcbutton.setObjectName("Celcbutton")
        self.result2 = QtWidgets.QLabel(self.centralwidget)
        self.result2.setGeometry(QtCore.QRect(270, 330, 281, 21))
        self.result2.setText("")
        self.result2.setObjectName("result2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 764, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fahrenlabel.setText(_translate("MainWindow", "Fahrenheit :"))
        self.label_2.setText(_translate("MainWindow", "Celsius : "))
        self.Fahrenbutton.setText(_translate("MainWindow", "Calculate"))
        self.Celcbutton.setText(_translate("MainWindow", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
